name = "gleam_dagger"
version = "0.9.6"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Dagger SDK for Gleam"
licences = ["Apache-2.0"]
links = [{title = "Dagger", href = "https://dagger.io"}]
repository = {type = "github", user = "fluentci-io", repo = "daggerverse"}

[dependencies]
envoy = "~> 1.0"
glance = "~> 0.8"
gleam_hackney = "~> 1.2"
gleam_http = "~> 3.5"
gleam_json = "~> 0.7"
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 1.0"
